### PR TITLE
timeout

### LINKED ISSUE #76: Timeout::Error: execution expired
```
Timeout::Error: execution expired
  from net/protocol.rb:158:in `wait_readable'
  from net/protocol.rb:158:in `rbuf_fill'
  from net/protocol.rb:136:in `readuntil'
  from net/protocol.rb:146:in `readline'
  from net/http/response.rb:40:in `read_status_line'
  from net/http/response.rb:29:in `read_new'
  from seahorse/client/net_http/patches.rb:29:in `block in new_transport_request'
  from seahorse/client/net_http/patches.rb:26:in `catch'
  from seahorse/client/net_http/patches.rb:26:in `new_transport_request'
  from net/http.rb:1407:in `request'
  from net/http.rb:1400:in `block in request'
  from net/http.rb:853:in `start'
  from net/http.rb:1398:in `request'
  from /app/objects/resource.rb:47:in `block in take'
  from timeout.rb:106:in `timeout'
  from /app/objects/resource.rb:46:in `take'
  from /app/objects/proxied_resource.rb:42:in `block in take'
  from /app/objects/proxied_resource.rb:40:in `each'
  from /app/objects/proxied_resource.rb:40:in `take'
  from /app/objects/endpoint.rb:114:in `ping'
  from /app/objects/base.rb:54:in `block in ping'
  from /app/objects/base.rb:54:in `map'
  from /app/objects/base.rb:54:in `ping'
  from /app/sixnines.rb:279:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from /app/sixnines.rb:276:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

### PR DESCRIPTION
**Pull request by pdacostaporto**
Fixes #76.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#80` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @pdacostaporto, total is [+45](http://www.0crat.com/u/pdacostaporto).

File: objects/resource.rb [hunk 1]
```diff
@@ -47,6 +47,8 @@ def take(host = nil, port = nil)
         http.request(req)
       end
       [res.code.to_i, res.body, to_text(req, res)]
+    rescue Timeout::Error
+      [500, '', 'The request timed out after 5 seconds.']
```
Comment (yegor256) [inline objects/resource.rb]: @pdacostaporto you're using number `5` here and the same number a few lines above. That's a code duplication. If in the future I change the number above, this one won't be changed and it will be a bug. It's better either to introduce a constant or get the real timeout value from the error

**Comment by yegor256** [comment]
@pdacostaporto see above

**Comment by pdacostaporto** [comment]
@yegor256 done.

**Comment by yegor256** [comment]
@rultor merge

**Comment by pdacostaporto** [comment]
@yegor256 should I do something about the failing merge? Looks like the container is failling to initialize because of outdated `apt` package info.

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor merge
